### PR TITLE
Update to PureScript 0.15.0

### PR DESCRIPTION
**Pull request by triallax**

### CODE REVIEW

**Comment by triallax** [comment]
@sharkdp this PR is ready now (just commenting in case you didn't get a notification, did you?).

**Comment by sharkdp** [comment]
Thank you!

**Comment by triallax** [comment]
Can you cut a new release so I can readd `purescript-quantities` to the package set?

**Comment by sharkdp** [comment]
I tried to follow the steps here: https://github.com/purescript/spago#publish-my-library

Bumping the version went fine (I pushed the changes and created a GitHub release), but `pulp publish` fails with:
```
▶ pulp publish
* ERROR: ENOENT: no such file or directory, scandir 'bower_components'
```
If I do `bower install`, resolve a lot of conflicts manually, `pulp publish` complains with "working tree dirty" (`bower_components` is not `.gitignored`).

**Comment by triallax** [comment]
Sorry, I lack the knowledge to help you. Perhaps you might get help on the PureScript Discourse or on [Spago's issue tracker](https://github.com/purescript/spago/issues/104)?

**Comment by JordanMartinez** [comment]
Try doing this
```
rm -rf bower_components/
bower cache clean
bower install
```
If the `bower_components` dir already exists, sometimes bower thinks it should use those versions instead of wiping it out completely. Also sometimes the bower cache gets in the way.

**Comment by sharkdp** [comment]
@JordanMartinez Thank you very much. It doesn't help, unfortunately. After `rm -rf bower_components; bower cache clean`:
```
> bower install
bower not-cached    https://github.com/sharkdp/purescript-decimals.git#^v7.0.0
bower resolve       https://github.com/sharkdp/purescript-decimals.git#^v7.0.0
bower not-cached    https://github.com/sharkdp/purescript-numbers.git#^v9.0.0
bower resolve       https://github.com/sharkdp/purescript-numbers.git#^v9.0.0
bower not-cached    https://github.com/paf31/purescript-lists.git#^v7.0.0
bower resolve       https://github.com/paf31/purescript-lists.git#^v7.0.0
bower not-cached    https://github.com/garyb/purescript-newtype.git#^v5.0.0
bower resolve       https://github.com/garyb/purescript-newtype.git#^v5.0.0
…
bower extract       purescript-exists#^6.0.0 archive.tar.gz
bower resolved      https://github.com/paf31/purescript-exists.git#6.0.0
bower extract       purescript-exists#^5.0.0 archive.tar.gz
bower resolved      https://github.com/paf31/purescript-exists.git#5.1.0

Unable to find a suitable version for purescript-foldable-traversable, please choose one by typing one of the numbers below:
    1) purescript-foldable-traversable#^5.0.0 which resolved to 5.0.1 and is required by purescript-arrays#6.0.1, purescript-gen#3.0.0, purescript-lazy#5.0.0, purescript-lists#6.1.0, purescript-nonempty#6.1.0, purescript-pairs#8.0.0, purescript-quickcheck#7.1.0, purescript-strings#5.0.0, purescript-transformers#5.2.0, purescript-unfoldable#5.0.0
    2) purescript-foldable-traversable#^6.0.0 which resolved to 6.0.0 and is required by purescript-lazy#6.0.0, purescript-lists#7.0.0, purescript-nonempty#7.0.0, purescript-unfoldable#6.0.0
    3) purescript-foldable-traversable#^v6.0.0 which resolved to 6.0.0 and is required by purescript-quantities

Prefix the choice with ! to persist it to bower.json

? Answer 
```

If I answer these questions, there are many others popping up afterwards...

**Comment by triallax** [comment]
Maybe it has something to do with [`purescript-pairs`'s `bower.json`](https://github.com/sharkdp/purescript-pairs/blob/97ae3cce9b0e00ff9473fff2779fcbcb4d7bc597/bower.json)? The versions in the file seem to be outdated.

**Comment by JordanMartinez** [comment]
That's it! See how it depends on `foldable-traversable@5.0.0` but here we depend on `foldable-traversable@6.0.0`? `pairs` needs to be updated before this repo's docs can be published.

**Comment by sharkdp** [comment]
Awesome - thank you guys! We now have a proper new version: https://pursuit.purescript.org/packages/purescript-quantities/12.0.1

**Pull request merged**
