### PR TITLE
Update for PureScript 0.12

### PR DESCRIPTION
**Pull request by abaco**
Just a straightforward update of dependencies and a couple of minor fixes.

### CODE REVIEW

**Review by sharkdp — APPROVED** [review]
Thank you so much!

**Comment by sharkdp** [comment]
Were you able to run the test-suite? I get the following:

```
> pulp test
[..]

* Running tests...
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '../Control.Semigroupoid/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/shark/Dropbox/Informatik/purescript/purescript-quantities/output/Control.Category/index.js:3:28)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
* ERROR: Subcommand terminated with exit code 1

```

**Comment by abaco** [comment]
Yes, the tests run fine to me! I've just checked again: removed bower_components and node_modules, reinstalled the dependencies, and run the tests. It works. Let me know if I can help in debugging.

**Comment by sharkdp** [comment]
I have no idea what went wrong. Repeated the same process today and it works. Thanks again!

Released as v8.0

**Pull request merged**
