### PR TITLE
Allow dimensional arguments for atan2 - part 2

### PR DESCRIPTION
**Pull request by imacg**
Fix for bug introduced by original PR and tests covering atan2.
 
Original PR #31

### CODE REVIEW

**Comment by sharkdp** [comment]
I have rebased the branch in your original PR. That is why the two first commits show up again (and it shows that it cannot be merged).

It is usually best to synchronize your fork first.

Do you want to try to fix this on your own (rebase your changes on my master branch, let me know if you need any help with Git)?  If not, I can also fix it myself.

**Comment by imacg** [comment]
I've rebased my branch onto of your master.

**Comment by sharkdp** [comment]
Thanks!

**Comment by imacg** [comment]
My pleasure. Thanks for your help and patience.

**Comment by sharkdp** [comment]
Released as v7.2.0.


Congrats on your first open source contribution!

**Pull request merged**
