### PR TITLE
Allow non-scalar arguments to atan2 when dimensions match

### PR DESCRIPTION
**Pull request by imacg**
Fix atan2 to allow arguments with the same dimensions and remove duplicate code.

### CODE REVIEW

**Review by sharkdp — APPROVED** [review]
Great work, thank you very much!!

I think we can remove the old `lift2` function (it is not exported and not used anywhere) and rename your new implementation from `lift2'` to `lift2`.

**Comment by imacg** [comment]
Thanks. Sorry for missing the dead function.

**Review by sharkdp — APPROVED** [review]

**Comment by sharkdp** [comment]
Thank you!

**Comment by sharkdp** [comment]
Oh - my bad: I should have checked it more thoroughly before merging.

Your changes are great for `max2`, `min2`, and `modulo`, but `atan2` has to be handled differently, I think.

Conceptually, `atan2(y, x)` is like `atan(y/x)`. So we want `y` and `x` to have compatible units, however: the result is dimensionless!

**Comment by sharkdp** [comment]
Unfortunately, we didn't have any tests for `atan2`. We should add something like this (somewhere around [here](https://github.com/sharkdp/purescript-quantities/blob/1cf287d9101cf20e6badbb759731f5a1defe33b9/test/Main.purs#L488)):
``` purs
    test "atan2" do
      almostEqual' (scalar (Math.pi / 4.0)) ((100.0 .* centi meter) `atan2` (1.0 .* meter))

```

**Comment by imacg** [comment]
I've fixed the issue and added a few tests. Unfortunately since I deleted my branch before your comment this PR isn't tracking my changes; are you able to edit this PR or should I open a new one?

Thanks for your patients.

**Comment by sharkdp** [comment]
Please open a new PR. Thank you very much!

**Pull request merged**
